# modules/home/misc/solaar.nix — Solaar user rules
# Places rules.yaml at ~/.config/solaar/rules.yaml via in-repo source.
# solaar-config.yaml is device-serial-specific and regenerated by Solaar — omitted.
{
  config,
  lib,
  ...
}:
let
  cfg = config.myHome.solaar;
in
{
  options.myHome.solaar.enable = lib.mkEnableOption "Solaar rules";

  config = lib.mkIf cfg.enable {
    xdg.configFile."solaar/rules.yaml".source = ./solaar-rules.yaml;
  };
}
